Add culture option to TypeConverterHelper, TextPrompt and AnsiConsole
spectreconsole/spectre.console pull request #1014
Opened 2022-10-14 12:03 UTC by sowa705

Useful feature if you want to enforce culture specific formatting (ex. DateTime)

2022-10-14 12:03 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/spectreconsole/spectre.console?pullRequest=1014) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/spectreconsole/spectre.console?pullRequest=1014) before we can accept your contribution.<br/><br/>:x: sowa705 [sign now](https://cla.dotnetfoundation.org/spectreconsole/spectre.console?pullRequest=1014)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/spectreconsole/spectre.console?pullRequest=1014) it.</sub>

2022-10-15 04:44 UTC, patriksvensson requested changes
LGTM, but I think that `TextPrompt<T>` also will need to implement the `IHasCulture` interface.

2022-10-15 09:19 UTC, patriksvensson approved these changes
LGTM 👍

2022-10-15 09:19 UTC, merged

2022-10-15 09:19 UTC, patriksvensson commented
Merged! Thank you for your contribution. Much appreciated! 👍