Automatically display default values of options in the help page
spectreconsole/spectre.console pull request #1032
Opened 2022-10-28 08:38 UTC by 0xced

Fixes #973

2022-12-11 14:09 UTC, FrankRay78 commented
Thank you for your contribution @0xced, just to let you know that I intend to review this PR over the coming weeks.

2022-12-18 15:17 UTC, FrankRay78 commented
I think your spectre.console\test\Spectre.Console.Cli.Tests\Expectations\Help\Command_Disable_Options_Default_Values.Output.verified.txt file needs to be check-in / with content @0xced

2022-12-23 20:07 UTC, FrankRay78 requested changes

2022-12-23 20:07 UTC, FrankRay78 commented on src/Spectre.Console.Cli/ICommandAppSettings.cs
> +    bool EnableOptionsDefaultValues { get; set; }
I would strongly recommend this property is renamed to one of the following (or similar): 

`ShowOptionsDefaultValues` 
`ShowOptionDefaultValues` <-- PROBABLY my preference, seeing them all laid out here. 
`DisplayOptionsDefaultValues`  
`DisplayOptionDefaultValues`    
`IncludeDefaultValuesHelp`
`PrintDefaultValuesHelp`

Rationale: The use of the word **Enable** may well be confused with actually turning off the use of default values when running a command.

Whatever the terminology decided here, there needs to be a meaningful "reverse" which allows the user to hide them being displayed in help.  It's the following ConfiguratorExtensions.cs method that would need to be renamed:

eg. from `public static IConfigurator DisableOptionsDefaultValues(this IConfigurator configurator)` 

to `public static IConfigurator HideOptionDefaultValues(this IConfigurator configurator)` 

Any thoughts @phil-scott-78  ?

2022-12-23 20:07 UTC, FrankRay78 commented on src/Spectre.Console.Cli/ConfiguratorExtensions.cs
> +    public static IConfigurator DisableOptionsDefaultValues(this IConfigurator configurator)
See my review comment in `src/Spectre.Console.Cli/ICommandAppSettings.cs` about the naming convention of `bool EnableOptionsDefaultValues { get; set; }`  

Once decided, this will need to be updated accordingly, removing the use of Disable in the method name.

2022-12-23 20:07 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Internal/Configuration/CommandAppSettings.cs
> +    public bool EnableOptionsDefaultValues { get; set; }
nb. This (and all uses of it) may need to be renamed, depending on what is decided in my review comment in `src/Spectre.Console.Cli/ICommandAppSettings.cs` about the naming convention of `bool EnableOptionsDefaultValues { get; set; }`

2022-12-23 21:59 UTC, 0xced commented on src/Spectre.Console.Cli/Internal/HelpWriter.cs
> +            columns.Add(option.Description?.TrimEnd('.') ?? " ");
Actually, supporting markup in the description is a feature. See for example the `RunCommand` class from the `Demo` example project. We can find several examples of markup in there:

```csharp
[CommandOption("--no-build")]
[Description("Do not build the project before running. Implies [grey]--no-restore[/].")]
public bool NoBuild { get; set; }
```

```csharp
[CommandOption("--verbosity <VERBOSITY>")]
[Description("Set the MSBuild verbosity level. Allowed values are q[grey]uiet[/], m[grey]inimal[/], n[grey]ormal[/], d[grey]etailed[/], and diag[grey]nostic[/].")]
[TypeConverter(typeof(VerbosityConverter))]
[DefaultValue(Verbosity.Normal)]
public Verbosity Verbosity { get; set; }
```

So if one needs a `]` in the description, it must be escaped with `]]` in the description itself.

2022-12-23 22:12 UTC, 0xced commented on src/Spectre.Console.Cli/ICommandAppSettings.cs
> +    /// Gets or sets a value indicating whether displaying or not the options default values in the help text.
Done in ee0c07fb4c9ad35145152791b4d738bcd56260a8.

2022-12-23 22:34 UTC, 0xced commented on src/Spectre.Console.Cli/ICommandAppSettings.cs
> +    bool EnableOptionsDefaultValues { get; set; }
I agree that Enable/Disable is probably not the best naming and could be confusing. I also agree that `ShowOptionDefaultValues` would be a better name but I don't like its opposite `HideOptionDefaultValues()` as the column is not really _hidden_ but rather _not displayed_ at all.

I think I'd prefer `IncludeOptionDefaultValues` / `ExcludeOptionDefaultValues()` but I'm not 100% convinced either so any input from @phil-scott-78 and/or @patriksvensson would be very welcome to help us decide the best name. 😉

2022-12-27 11:17 UTC, FrankRay78 commented on src/Spectre.Console.Cli/ICommandAppSettings.cs
> +    bool EnableOptionsDefaultValues { get; set; }
Thanks for your changes @0xced so far, we are very close to having this ready to merge now.  Personally, I'm ok with using Show/Hide prefixes, as from the end user's POV that is what happens.  If you want to adopt that, I'd be happy to merge this issue. Otherwise, I'm also ok with waiting for a second opinion from one of the other maintainers.

2022-12-28 10:13 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Internal/HelpWriter.cs
> +            columns.Add(option.Description?.TrimEnd('.') ?? " ");
Yes of course, my bad.  Well explained.  I'll resolve this.

2022-12-28 16:39 UTC, 0xced commented on src/Spectre.Console.Cli/ICommandAppSettings.cs
> +    bool EnableOptionsDefaultValues { get; set; }
I went with in `ShowOptionDefaultValues` / `HideOptionDefaultValues()` in 0d14daf191753340e563ff42084c428936d73209 which is indeed better than `EnableOptionsDefaultValues` / `DisableOptionsDefaultValues()`.

2022-12-28 20:25 UTC, FrankRay78 approved these changes

2022-12-28 20:28 UTC, merged

2022-12-28 20:29 UTC, FrankRay78 commented
Thank you @0xced - a seriously good contribution you've made here.

2022-12-28 21:57 UTC, 0xced commented
Oops, it looks like there's an [issue with the NuGet API key](https://github.com/spectreconsole/spectre.console/actions/runs/3796430990/jobs/6456568441):

> Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.)

2022-12-29 10:10 UTC, FrankRay78 commented
Thanks, I'll ping Patrik about this...

2022-12-29 16:51 UTC, patriksvensson commented
@FrankRay78 @0xced I'm on it