Added documentation for CaseSensitivity in commandApp.md and settings.md
spectreconsole/spectre.console pull request #1042
Opened 2022-11-01 23:10 UTC by alex-eshock

Fixes #653 where CaseSensitivity has now been documented in the respective .md files.

2022-11-01 23:11 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/spectreconsole/spectre.console?pullRequest=1042) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/spectreconsole/spectre.console?pullRequest=1042) before we can accept your contribution.<br/><br/>:x: alex-eshock [sign now](https://cla.dotnetfoundation.org/spectreconsole/spectre.console?pullRequest=1042)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/spectreconsole/spectre.console?pullRequest=1042) it.</sub>

2022-11-03 01:54 UTC, alex-eshock commented
Hold on I made a mistake. I'm going to close the pull request and create a new one.

2022-11-03 02:01 UTC, alex-eshock commented
Fixes https://github.com/spectreconsole/spectre.console/issues/653 where CaseSensitivity has now been documented in the respective .md files.

2022-11-04 08:20 UTC, patriksvensson requested changes

2022-11-04 08:20 UTC, patriksvensson commented on docs/input/cli/commandApp.md
> +
I think this doesn't seem right. Commands that we provide to an application, such as `myexe.com mycommand` are case sensitive in the sense that `myexe.com Mycommand` (notice the capital 'M') would not match the configured command.

There is no preference when it comes to naming of commands.

2022-11-04 08:20 UTC, patriksvensson commented on docs/input/cli/settings.md
> +
I think this doesn't seem right. Options that we provide to an application such as `myexe.com --myoption 1` are case sensitive in the sense that `myexe.com --Myoption 1` (notice the capital 'M') would not match the configured option.

There is no preference when it comes to naming of settings.

2022-11-18 01:20 UTC, closed without merging