Added Test Cases For Asynchronous Methods/Commands to Resolve Issue 676
spectreconsole/spectre.console pull request #1049
Opened 2022-11-04 01:03 UTC by alex-eshock

Fixes #676 where there were little to no test cases that tested asynchronicity within the application.

I've implemented 2 test classes that have multiple test cases that are similar to `CommandAppTest` classes to provide a more tangible example between asynchronous and synchronous runtime.
- `AsyncCommandTest.cs`
- `AsyncCommandTests.Exceptions.cs`

@wguner also implemented a class that serves as the base for testing asynchronous commands called `AsyncTester.cs`.

2022-11-04 08:16 UTC, patriksvensson requested changes

2022-11-04 08:16 UTC, patriksvensson commented on docs/input/cli/commandApp.md
> +Commands are in `PascalCase`, also known as `UpperCamelCase`.
Are these changes related to #653?

I think this doesn't seem right. Commands that we provide to an application such `myexe.com command --option 1` are case sensitive in the sense that `myexe.com Command --option 1` (notice the capital 'C') would return an error if the command was named `command`. It's not the `Command` class that is case sensitive.

2022-11-04 08:16 UTC, patriksvensson commented on docs/input/cli/settings.md
> +CommandsSettings are in `PascalCase`, also known as `UpperCamelCase`.
Are these changes related to #653?

I think this doesn't seem right. Commands that we provide to an application such `myexe.com command --option 1` are case sensitive in the sense that `myexe.com Command --option 1` (notice the capital 'C') would return an error if the command was named `command`. It's not the `Command` class that is case sensitive.

2022-11-04 08:16 UTC, patriksvensson commented on docs/input/cli/settings.md
> +`NOTE:` There can only be one `argument vector`, and it needs to be the last argument of the command.
@phil-scott-78 Is this correct?

2022-11-04 08:16 UTC, patriksvensson commented on src/Spectre.Console.Testing/Cli/AsyncTester.cs
> +public class AsyncTester
I don't think we need a whole new class for this. The old `CommandAppTester` could be augmented with a `RunAsync` method instead.

2022-11-04 08:23 UTC, patriksvensson commented on docs/input/cli/settings.md
> +`NOTE:` There can only be one `argument vector`, and it needs to be the last argument of the command.
I think this belongs to PR #1045 and has accidentally been included.

2022-12-09 03:56 UTC, alex-eshock commented on docs/input/cli/commandApp.md
> +Commands are in `PascalCase`, also known as `UpperCamelCase`.
I just removed the documentation i accidentally added. Things should be good from here.

2022-12-09 03:56 UTC, alex-eshock commented on docs/input/cli/settings.md
> +CommandsSettings are in `PascalCase`, also known as `UpperCamelCase`.
I just removed the documentation i accidentally added. Things should be good from here.

2022-12-09 03:56 UTC, alex-eshock commented on docs/input/cli/settings.md
> +`NOTE:` There can only be one `argument vector`, and it needs to be the last argument of the command.
I just removed the documentation i accidentally added. Things should be good from here.

2022-12-09 03:57 UTC, alex-eshock commented on src/Spectre.Console.Testing/Cli/AsyncTester.cs
> +public class AsyncTester
I moved some of the class contents to `CommandAppTester` and made a `RunAsync` method within that class. I have removed the `AsyncTester.cs` class as well.

2023-05-17 10:21 UTC, FrankRay78 commented
I'm closing this PR given it's age, the unresolved review comments and the underlying progress of the main branch. Thank you @alex-eshock for your efforts and feel free to contribute to spectre.console again in the future.

2023-05-17 10:21 UTC, closed without merging