Allow configuration of confirmation prompt comparison via `StringComparer`
spectreconsole/spectre.console pull request #1161
Opened 2023-02-11 15:59 UTC by MartinZikmund

2023-02-11 16:38 UTC, patriksvensson requested changes

2023-02-11 16:38 UTC, patriksvensson commented on src/Spectre.Console/Prompts/ConfirmationPrompt.cs
> +    public StringComparer ChoiceComparer { get; set; } = StringComparer.CurrentCultureIgnoreCase;
Perhaps we can just call it `Comparer`.

2023-02-11 16:38 UTC, patriksvensson commented on src/Spectre.Console/Prompts/ConfirmationPrompt.cs
> +        return ChoiceComparer.Compare(Yes.ToString(), result.ToString()) == 0;
The comparer might be null here, so we need to fall back on the case-insensitive one if it is.

2023-03-16 08:49 UTC, MartinZikmund commented
@patriksvensson Sorry for the delay, made adjustments 👍

2023-03-16 08:50 UTC, patriksvensson commented
@MartinZikmund No worries. No SLA for open source contributions 😉

2023-03-16 08:57 UTC, patriksvensson approved these changes

2023-03-16 08:57 UTC, merged

2023-03-16 08:57 UTC, patriksvensson commented
Merged! Thank you for your contribution. Much appreciated! 👍