HelpProvider supports localisation
spectreconsole/spectre.console pull request #1349
Opened 2023-10-30 16:17 UTC by FrankRay78

+ Extracted hardcoded strings into a default resource file
+ Included localised strings for French
+ Wrote unit tests for both

2023-11-02 14:29 UTC, FrankRay78 commented
@patriksvensson - I've removed the need to set the culture on the current thread by eliminating statics, and so ensured that no funny business will happen when parallel running tests.

2023-11-03 21:06 UTC, nils-a approved these changes
Two minor changes, but generally LGTM!

2023-11-03 21:06 UTC, nils-a commented on test/Spectre.Console.Cli.Tests/Unit/CommandAppTests.Help.cs
> +            return Verifier.Verify(result.Output, settings);
I think it should be possible to re-use the `EN` method like this:

```suggestion
           return  Should_Output_Default_Command_And_Additional_Commands_When_Default_Command_Has_Required_Parameters_And_Is_Called_Without_Args_EN(culture);
```

That would spare me copying the content for a third time when I add the German translation.

2023-11-03 21:06 UTC, nils-a commented on test/Spectre.Console.Cli.Tests/Unit/CommandAppTests.Help.cs
> +using System.Diagnostics.SymbolStore;
I think this line is not needed.

2023-11-03 22:10 UTC, patriksvensson requested changes
A minor thing that I think we should dicuss.

2023-11-03 22:10 UTC, patriksvensson commented on src/Spectre.Console.Cli/ConfiguratorExtensions.cs
> +    public static IConfigurator SetApplicationCulture(this IConfigurator configurator, string culture)
Perhaps we could use a `CultureInfo` here instead and take the culture from that instance.

That way we won't need to document what a valid culture name is or is not.

2023-11-04 10:44 UTC, FrankRay78 commented on test/Spectre.Console.Cli.Tests/Unit/CommandAppTests.Help.cs
> +using System.Diagnostics.SymbolStore;
Agreed.

2023-11-04 10:51 UTC, FrankRay78 commented on test/Spectre.Console.Cli.Tests/Unit/CommandAppTests.Help.cs
> +            return Verifier.Verify(result.Output, settings);
You mean collapsing both of these tests together @nils-a ?

```csharp
        // Localised version of the above test, in English
        [Theory]
        [InlineData(null)]
        [InlineData("")]
        [InlineData("en")]
        [InlineData("en-EN")]
        [Expectation("Default_Without_Args_Additional")]
        public Task Should_Output_Default_Command_And_Additional_Commands_When_Default_Command_Has_Required_Parameters_And_Is_Called_Without_Args_EN(string culture)
```

and

```csharp
        // Localised version of the above test, in French
        [Theory]
        [InlineData("fr")]
        [InlineData("fr-FR")]
        [Expectation("Default_Without_Args_Additional-FR")]
        public Task Should_Output_Default_Command_And_Additional_Commands_When_Default_Command_Has_Required_Parameters_And_Is_Called_Without_Args_FR(string culture)
```

I think an elegant solution might be to dynamically vary the expectation by appending the culture name to something like "Default_Without_Args_Additional-"

However, the following cases:

        [InlineData(null)]
        [InlineData("")]

Might actually need to become something like:

        [InlineData(null, "en")]
        [InlineData("", "en")]

In order to qualify the localisation result we expect ie. qualifying the expectation.

2023-11-04 10:53 UTC, FrankRay78 commented
@patriksvensson , @nils-a

FYI. If you provide me with the localised strings for the following in your own language, along with the culture, I can see about pushing these into this branch ahead of merging:

Prints help information
Prints version information
DESCRIPTION
USAGE
OPTIONS
COMMAND
COMMANDS
EXAMPLES
ARGUMENTS
DEFAULT

2023-11-04 12:04 UTC, patriksvensson commented
Sure!

**Prints help information**
Skriver ut hjälpinformatiob
 **Prints version information**
Skriver ut versionsnummer
 **DESCRIPTION**
BESKRIVNING
 **USAGE**
ANVÄNDING
 **OPTIONS**
VAL
 **COMMAND**
KOMMANDO
 **COMMANDS**
KOMMANDON
 **EXAMPLES**
EXEMPEL
 **ARGUMENTS**
ARGUMENT
 **DEFAULT**
STANDARD

2023-11-04 21:29 UTC, nils-a commented
en | de
--|--
Prints help information | Zeigt Hilfe an
Prints version information | Zeigt Versionsinformationen an
DESCRIPTION | BESCHREIBUNG
USAGE | VERWENDUNG
OPTIONS | OPTIONEN
COMMAND | KOMMANDO
COMMANDS | KOMMANDOS
EXAMPLES | BEISPIELE
ARGUMENTS | ARGUMENTE
DEFAULT | STANDARDWERT

2023-11-05 18:38 UTC, 0xced commented
For French I'd go _slightly_ less verbose.

en | fr
--|--
Prints help information | _Affiche l'aide_
Prints version information | _Affiche la version_
USAGE | UTILISATION (was missing in the screenshot)

2023-11-05 18:45 UTC, 0xced commented on src/Spectre.Console.Cli/ICommandAppSettings.cs
> +    /// Gets or sets the culture.
We should document what culture is used by default (i.e. when `null`)

2023-11-05 18:46 UTC, 0xced commented on src/Spectre.Console.Cli/ICommandAppSettings.cs
> +    /// Gets or sets the culture.
Or even change this property to a non nullable `CultureInfo` (as already mentioned by Patrick elsewhere) but document what's the default value anyway.

2023-11-05 22:52 UTC, FrankRay78 commented on src/Spectre.Console.Cli/ICommandAppSettings.cs
> +    /// Gets or sets the culture.
I added the following:

```csharp
    /// <summary>
    /// Gets or sets the culture.
    /// </summary>
    /// <remarks>
    /// Text displayed by <see cref="Help.HelpProvider"/> can be localised, but defaults to English.
    /// Setting this property informs the resource manager which culture to use when fetching strings.
    /// English will be used when a culture has not been specified (ie. this property is null)
    /// or a string has not been localised for the specified culture.
    /// </remarks>
    CultureInfo? Culture { get; set; }
```

Do you think it sufficiently documents the behaviour @0xced ?

2023-11-05 22:56 UTC, FrankRay78 commented
@patriksvensson, @nils-a, @0xced - I believe the latest push addresses your excellent review comments, as well as updating the French translations (as suggested) and adding Swedish and German localisations.

2023-11-05 22:58 UTC, FrankRay78 reviewed
I'm happy with the changes.

2023-11-05 23:38 UTC, patriksvensson approved these changes

2023-11-05 23:43 UTC, 0xced commented on src/Spectre.Console.Cli/ICommandAppSettings.cs
> +    /// Gets or sets the culture.
Yes, that's very good! I think this remark should also be added to the `ConfiguratorExtensions.SetApplicationCulture` method because currently, _Sets the culture for the application._ could be confusing.

2023-11-05 23:48 UTC, 0xced commented on src/Spectre.Console.Cli/Resources/HelpProvider.fr.resx
> +  <data name="Command" xml:space="preserve">
I think `ARGUMENTS`, `DESCRIPTION` and `OPTIONS` should be added to the French translation, even if they are the exact same words. This makes it clear that the localisation was not forgotten. Also, Rider emits warnings saying that it's missing French translations for those 3 elements.

2023-11-06 09:16 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Resources/HelpProvider.fr.resx
> +  <data name="Command" xml:space="preserve">
I will make these changes later today @0xced, then you will be free to review and merge.

2023-11-06 12:27 UTC, nils-a commented on test/Spectre.Console.Cli.Tests/Spectre.Console.Cli.Tests.csproj
>    <ItemGroup>
I'm nit-picking here, but, looking at it now, I feel this whole `ItemGroup` is not really needed.

2023-11-06 22:31 UTC, FrankRay78 commented on test/Spectre.Console.Cli.Tests/Spectre.Console.Cli.Tests.csproj
>    <ItemGroup>
note to self: Never try and sneak anything past @nils-a , he will find out.

2023-11-06 22:44 UTC, FrankRay78 commented
@0xced Addressed all further review comments in the latest push.

2023-11-09 11:45 UTC, 0xced commented on src/Spectre.Console.Cli/ConfiguratorExtensions.cs
> +    public static IConfigurator SetApplicationCulture(this IConfigurator configurator, CultureInfo culture)
I think we should either explicitly allow a `null` culture (by changing `CultureInfo` into `CultureInfo?` and adapting the documentation of the `culture` parameter) or throw an `ArgumentNullException`. Currently, the test code emits a warning (_Possible 'null' assignment to non-nullable entity_) but actually executes fine, even when `null` is passed:

```csharp
configurator.SetApplicationCulture(string.IsNullOrEmpty(culture) ? null : new CultureInfo(culture))
```

I'm not sure which option is best. I'm trying to think about how it's going to be used at the application level, probably something like this:
```csharp
if (userPrefersLocalizedCli)
{
    configurator.SetApplicationCulture(CultureInfo.CurrentUICulture)
}
```

This use case would imply throwing an `ArgumentNullException` but my gut feeling says `CultureInfo?` is fine so I'm happy to hear your opinions on this.

Thinking more about it, `userPrefersLocalizedCli` might be quite tricky to compute so it might end up being the developer's choice to unconditionally call `SetApplicationCulture(CultureInfo.CurrentUICulture)`. This raises the question if Spectre.Console.Cli should default to `CultureInfo.CurrentUICulture` instead of English.

Sorry for being so nitpicky about this pull request, Frank. 🫣

2023-11-09 11:55 UTC, 0xced commented on src/Spectre.Console.Cli/ConfiguratorExtensions.cs
> +    public static IConfigurator SetApplicationCulture(this IConfigurator configurator, CultureInfo culture)
After pondering two more minutes, I think we should throw `ArgumentNullException` because it doesn't make sense to call `SetApplicationCulture` with `null` since it's already the default. If you don't want to change the default then just don't call `SetApplicationCulture`. Seems sensible?

2023-11-09 11:57 UTC, 0xced commented on src/Spectre.Console.Cli/ConfiguratorExtensions.cs
> +    public static IConfigurator SetApplicationCulture(this IConfigurator configurator, CultureInfo culture)
And I think the corresponding tests could be merged into one single (slightly adapted) test.

```csharp
        [Theory]
        [InlineData(null, "EN")]
        [InlineData("iv", "EN")]
        [InlineData("en", "EN")]
        [InlineData("en-EN", "EN")]
        [InlineData("fr", "FR")]
        [InlineData("fr-FR", "FR")]
        [InlineData("sv", "SV")]
        [InlineData("sv-SE", "SV")]
        [InlineData("de", "DE")]
        [InlineData("de-DE", "DE")]
        [Expectation("Default_Without_Args_Additional")]
        public Task Should_Output_Default_Command_And_Additional_Commands_When_Default_Command_Has_Required_Parameters_And_Is_Called_Without_Args(string culture, string expectationPrefix)
        {
            // Given
            var fixture = new CommandAppTester();
            fixture.SetDefaultCommand<LionCommand>();
            fixture.Configure(configurator =>
            {
                configurator.AddExample("20", "--alive");
                configurator.SetApplicationName("myapp");
                configurator.AddCommand<GiraffeCommand>("giraffe");
                if (culture != null)
                {
                    configurator.SetApplicationCulture(CultureInfo.GetCultureInfo(culture));
                }
            });

            // When
            var result = fixture.Run();

            // Then
            return Verifier.Verify(result.Output).UseTextForParameters(expectationPrefix).DisableRequireUniquePrefix();
        }
```

And the `Default_Without_Args_Additional.Output.verified.txt` file can be deleted.

2023-11-09 13:30 UTC, FrankRay78 commented on src/Spectre.Console.Cli/ConfiguratorExtensions.cs
> +    public static IConfigurator SetApplicationCulture(this IConfigurator configurator, CultureInfo culture)
> After pondering two more minutes, I think we should throw `ArgumentNullException` because it doesn't make sense to call `SetApplicationCulture` with `null` since it's already the default. If you don't want to change the default then just don't call `SetApplicationCulture`. Seems sensible?

I was of the same opinion, and came to say as such.  But you beat me to it.  I don't mind the clarifications as we want to get it right.  

As an aside, I think Patrik was right to suggest the user sets the culture explicitly, rather than embed a possible call to fetch the Culture from the UI thread - ie. put the responsibility back on the developer to define exactly how it should operate.  I'll make the changes and do another push.

2023-11-09 15:02 UTC, patriksvensson commented on src/Spectre.Console.Cli/ConfiguratorExtensions.cs
> +    public static IConfigurator SetApplicationCulture(this IConfigurator configurator, CultureInfo culture)
I think we should accept null here. Perhaps the user want to change it or set the value dynamically somehow. We shouldn't throw.

2023-11-09 16:57 UTC, FrankRay78 commented on src/Spectre.Console.Cli/ConfiguratorExtensions.cs
> +    public static IConfigurator SetApplicationCulture(this IConfigurator configurator, CultureInfo culture)
Hi @patriksvensson, the fallback resource text is currently returned for a null culture. I guess what your suggestion does is allow the user to return to that state, if they wish to.

2023-11-09 18:00 UTC, patriksvensson commented on src/Spectre.Console.Cli/ConfiguratorExtensions.cs
> +    public static IConfigurator SetApplicationCulture(this IConfigurator configurator, CultureInfo culture)
Exactly, and it also makes it easier to set the value. Our other API:s in SC works this way.

Makes it possible to do:

```csharp
config.SetApplicationCulture(GetMyAppCulture())
```

Instead of:

```csharp
var culture = GetMyAppCulture();
if(culture != null)
{
    config.SetApplicationCulture(culture);
}
```

If the property is nullable, we should accept null for convenience methods.

2023-11-09 20:06 UTC, 0xced commented on src/Spectre.Console.Cli/ConfiguratorExtensions.cs
> +    public static IConfigurator SetApplicationCulture(this IConfigurator configurator, CultureInfo culture)
It would actually be hard to write a `GetMyAppCulture()` method that returns `null` since both `CultureInfo.CurrentUICulture` and `CultureInfo.GetCultureInfo()` return a non null `CultureInfo` but let's accept the nullable version since it's easier to use.

Just yesterday, I was bothered by the TextPromptExtensions methods `DefaultValueStyle()` and `ChoicesStyle()` that don't accept nullable Style instances while the underlying properties are nullable. I can be inconsistent sometimes. 😆

2023-11-10 07:02 UTC, patriksvensson commented on src/Spectre.Console.Cli/ConfiguratorExtensions.cs
> +    public static IConfigurator SetApplicationCulture(this IConfigurator configurator, CultureInfo culture)
Using those methods sure, but imagine if someone is doing a database lookup for a culture that the user set somehow, or checking some other configuration in a configuration file.

2023-11-10 12:58 UTC, FrankRay78 commented on src/Spectre.Console.Cli/ConfiguratorExtensions.cs
> +    public static IConfigurator SetApplicationCulture(this IConfigurator configurator, CultureInfo culture)
The latest push has made it nullable @patriksvensson, and also removed the redundant test @0xced .

2023-11-10 23:22 UTC, patriksvensson approved these changes

2023-11-10 23:22 UTC, merged

2024-12-18 20:19 UTC, Tolitech commented
Hello @patriksvensson,
I would like the HelpProvider to support some additional languages, as listed below.

![image](https://github.com/user-attachments/assets/b386ff93-2078-4a9a-a99e-67cec30fa82e)

Would it be possible for me to contribute by creating the Resource files that are not yet supported?

2024-12-19 09:30 UTC, FrankRay78 commented
Yes please @Tolitech! I can review and merge.

2024-12-19 12:09 UTC, Tolitech commented
Hello, @FrankRay78.
The changes have already been made in my FORK.
I have created 6 new resource files.
I have tested it locally and will submit the Pull Request soon.