Feat/barchart updates
spectreconsole/spectre.console pull request #1388
Opened 2023-11-28 20:57 UTC by jsheely

I'm going to start the process for this PR to make it add more clarity on the issue https://github.com/spectreconsole/spectre.console/issues/1382 raised to see exactly what was changed and to start the conversation

Key points
- Added `ValueFormatter` for bar chart based on breakdown chart
- Added label color option

- [x] I have read the [Contribution Guidelines](../CONTRIBUTING.md)
- [x] I have commented on the issue above and discussed the intended changes
- [x] A maintainer has signed off on the changes and the issue was assigned to me
- [x] All newly added code is adequately covered by tests
- [x] All existing tests are still running without errors
- [x] The documentation was modified to reflect the changes _OR_ no documentation changes are required.

---
Please upvote :+1: this pull request if you are interested in it.

2023-11-28 21:01 UTC, jsheely commented
@microsoft-github-policy-service agree

2023-11-28 21:46 UTC, patriksvensson requested changes
We need to cover the new functionality with some tests and update the documentation for the BarChart. I also think that the Progress bar changes should be moved to its own PR.

Also, we will need you to fill out the PR template as part of the PR. You can find it here: https://raw.githubusercontent.com/spectreconsole/spectre.console/main/.github/pull_request_template.md

2023-11-28 21:46 UTC, patriksvensson commented on src/Spectre.Console/Widgets/Charts/IBarChartItem.cs
> +    Color? LabelColor { get; }
I think a `Style` would be more suitable here since labels are text.

2023-11-28 21:46 UTC, patriksvensson commented on src/Spectre.Console/Widgets/ProgressBar.cs
Would prefer these changes to be in its own PR

2023-11-28 21:46 UTC, patriksvensson commented on src/Spectre.Console/Spectre.Console.sln
I suspect these changes aren't necessary

2023-11-29 16:19 UTC, jsheely commented on src/Spectre.Console/Spectre.Console.sln
Concur. New C# Dev Kit solution updates gone wild.

2023-11-29 16:19 UTC, jsheely commented on src/Spectre.Console/Widgets/ProgressBar.cs
Okay I can break up the changes by "component" so that this one is isolated to just the barchart and will make others for the dependencies.

2023-11-29 16:20 UTC, jsheely commented on src/Spectre.Console/Widgets/Charts/IBarChartItem.cs
> +    Color? LabelColor { get; }
Okay will look into Style vs Color option for this. I wanted to simply match the pattern that is used for the progress bar color originally for simplicity.

2023-12-26 15:31 UTC, patriksvensson requested changes

2023-12-26 15:31 UTC, patriksvensson commented on src/Spectre.Console/Spectre.Console.sln
I suspect this shouldn't be changed.

2023-12-26 15:31 UTC, patriksvensson commented on src/Spectre.Console/Extensions/BarChartExtensions.cs
> +    public static BarChart AddItem(this BarChart chart, string label, double value, Color? color = null, Style? labelColor = null)
`labelColor` should be called `labelStyle`

2023-12-26 15:31 UTC, patriksvensson commented on src/Spectre.Console/Extensions/BarChartExtensions.cs
> +        chart.Data.Add(new BarChartItem(label, value, color, labelColor));
`labelColor` should be called `labelStyle`

2023-12-26 15:40 UTC, patriksvensson commented
We will also need to update the documentation so it reflect the new additions.

2024-01-31 16:46 UTC, patriksvensson requested changes

2024-01-31 16:46 UTC, patriksvensson commented on docs/input/widgets/barchart.md
> +### Addd items with bar and label style
`Add` has a spelling mistake

2024-01-31 16:46 UTC, patriksvensson commented on src/Spectre.Console/Widgets/Charts/BarChart.cs
> +                item.LabelStyle != null ? new Text(item.Label, item.LabelStyle) : new Markup(item.Label),
Replace `Text` with `Markup` here.

2026-02-20 17:22 UTC, patriksvensson commented
Hi! 

Thanks so much for taking the time to submit this PR. 
I really appreciate the contribution!

Unfortunately, I haven’t had the capacity to review this in a timely manner, and since it was opened, the repository has changed significantly. Because of that, this PR is no longer in a state where it can be reviewed or merged as-is. This is not your fault, but mine, and I'm sorry about this.

I’m going to close it for now to help keep things tidy. That said, if you’re still interested in contributing, please feel free to open a new pull request that’s up to date with the current state of the repository, and I’ll be happy to take a look when I can. *I'll promise I'll do better this time around.*

Thanks again for your work and for your interest in the project!

2026-02-20 17:22 UTC, closed without merging