[DRAFT] HelpProvider colors should be configurable
spectreconsole/spectre.console pull request #1408
Opened 2023-12-20 17:10 UTC by FrankRay78

**DRAFT PR FOR DISCUSSION - DO NOT MERGE**

fixes #1379

- [ ] I have read the [Contribution Guidelines](../CONTRIBUTING.md)
- [ ] I have commented on the issue above and discussed the intended changes
- [ ] A maintainer has signed off on the changes and the issue was assigned to me
- [ ] All newly added code is adequately covered by tests
- [ ] All existing tests are still running without errors
- [ ] The documentation was modified to reflect the changes _OR_ no documentation changes are required.

## Changes

- All styles are written through the Composer class

2024-01-15 08:22 UTC, patriksvensson requested changes

2024-01-15 08:22 UTC, patriksvensson commented on src/Spectre.Console.Cli/ICommandAppSettings.cs
> +
I'm not sure about this, to be honest. `HelpProviderStyles` is tightly coupled to the `HelpProvider`, so the question is whether it shouldn't be part of that.

It should be nullable and not set by default if it must exist.

2024-01-15 08:22 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
Everything that's public needs to have XML documentation.

2024-01-15 08:22 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public struct DescriptionStyle
Why `Struct`?

2024-01-15 08:22 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public struct UsageStyle
Why `Struct`?

2024-01-15 08:22 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public struct ExampleStyle
Why `Struct`?

2024-01-15 08:22 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public struct ArgumentStyle
Why `Struct`?

2024-01-15 08:22 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public struct CommandStyle
Why `Struct`?

2024-01-15 08:22 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public struct OptionStyle
Why `Struct`?

2024-01-15 08:22 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +}
Please don't define a new type that collides with the existing `Style`. Use the existing `Style` type instead.

2024-01-15 08:22 UTC, patriksvensson commented on src/Spectre.Console.Cli/ICommandAppSettings.cs
> +    bool RenderMarkupInline { get; set; }
This seems to be unused. What is it for?

2024-01-15 08:22 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +    }
Not needed.

2024-01-15 08:22 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +}
Not needed.

2024-01-15 08:22 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +    }
Do not return a new instance every access.

2024-01-15 10:22 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +}
As per the example above, do we not want to offer users the following?

```charp
            // Render an unstyled help text for maximum accessibility
            config.Settings.HelpProviderStyles = HelpProviderStyle.None;
```

2024-01-15 16:53 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +}
We already support this via NO_COLORS, which is a "standardized" way of disabling colors. See https://no-color.org/

2024-01-17 22:06 UTC, FrankRay78 commented on src/Spectre.Console.Cli/ICommandAppSettings.cs
> +
It's now nullable, but set to the factory `HelpProviderStyle.Default` out of the box.  This preserves existing Spectre.console behaviour ie. styled output.  The documentation explains it can be set to a custom theme, or removed entirely to avoid styling - this is the behaviour asked for in the original github issue (https://github.com/spectreconsole/spectre.console/issues/1379).

2024-01-17 22:06 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
Done

2024-01-17 22:07 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public struct DescriptionStyle
Converted to object, and appropriate null handling added throughout the help provider rendering logic.

2024-01-17 22:07 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public struct UsageStyle
Converted to object, and appropriate null handling added throughout the help provider rendering logic.

2024-01-17 22:07 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public struct ExampleStyle
Converted to object, and appropriate null handling added throughout the help provider rendering logic.

2024-01-17 22:07 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public struct ArgumentStyle
Converted to object, and appropriate null handling added throughout the help provider rendering logic.

2024-01-17 22:07 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public struct CommandStyle
Converted to object, and appropriate null handling added throughout the help provider rendering logic.

2024-01-17 22:07 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public struct OptionStyle
Converted to object, and appropriate null handling added throughout the help provider rendering logic.

2024-01-17 22:08 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +}
Noted, and removed.

2024-01-17 22:08 UTC, FrankRay78 commented on src/Spectre.Console.Cli/ICommandAppSettings.cs
> +    bool RenderMarkupInline { get; set; }
Removed.

2024-01-17 22:08 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +    }
Used only for testing.  Now pushed into the unit test project, out of the main spectre.console library.

2024-01-17 22:13 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +    }
Agreed, code updated to only instantiate once.

2024-01-17 22:19 UTC, FrankRay78 commented
Major refactoring has now been done to address all review comments @patriksvensson, including a rewrite of the accompanying documentation. It's also now a PR I can be proud of. Happy to address any further issues stopping this from being merged.

2024-01-17 22:40 UTC, patriksvensson requested changes

2024-01-17 22:40 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +    }
```suggestion
    public static HelpProviderStyle Default { get; } = 
        new HelpProviderStyle()
        {
            Description = new DescriptionStyle()
            {
                Header = "yellow",
            },
            Usage = new UsageStyle()
            {
                Header = "yellow",
                CurrentCommand = "underline",
                Command = "aqua",
                Options = "grey",
                RequiredArgument = "aqua",
                OptionalArgument = "silver",
            },
            Examples = new ExampleStyle()
            {
                Header = "yellow",
                Arguments = "grey",
            },
            Arguments = new ArgumentStyle()
            {
                Header = "yellow",
                RequiredArgument = "silver",
                OptionalArgument = "silver",
            },
            Commands = new CommandStyle()
            {
                Header = "yellow",
                ChildCommand = "silver",
                RequiredArgument = "silver",
            },
            Options = new OptionStyle()
            {
                Header = "yellow",
                DefaultValueHeader = "lime",
                DefaultValue = "bold",
                RequiredOption = "silver",
                OptionalOption = "grey",
            },
        };
```

2024-01-17 22:40 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +    private static HelpProviderStyle? defaultStyle;
This can be removed if the suggestion below is applied.

2024-01-17 22:40 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public class HelpProviderStyle
Should be `sealed`

2024-01-17 22:40 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public class DescriptionStyle
Should be `sealed`

2024-01-17 22:40 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public class UsageStyle
Should be `sealed`

2024-01-17 22:40 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public class ExampleStyle
Should be `sealed`

2024-01-17 22:40 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public class ArgumentStyle
Should be `sealed`

2024-01-17 22:40 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public class CommandStyle
Should be `sealed`

2024-01-17 22:40 UTC, patriksvensson commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public class OptionStyle
Should be `sealed`

2024-01-17 22:40 UTC, patriksvensson commented on src/Spectre.Console.Cli/Internal/Composer.cs
> +    private readonly bool renderMarkup = false;
Member variables start with underscore `_`.

2024-01-17 22:40 UTC, patriksvensson commented on src/Spectre.Console.Cli/Internal/Composer.cs
> +    private readonly StringBuilder content;
Member variables start with underscore `_`.

2024-01-17 22:40 UTC, patriksvensson commented on src/Spectre.Console.Cli/Internal/Composer.cs
> +        this.renderMarkup = renderMarkup;
We don't use `this.`

2024-01-18 14:11 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +    }
Good suggestion, I agree.

2024-01-18 14:12 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public class OptionStyle
Done

2024-01-18 14:12 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Internal/Composer.cs
> +    private readonly bool renderMarkup = false;
Done

2024-01-18 14:12 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public class CommandStyle
Done

2024-01-18 14:13 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public class ArgumentStyle
Done

2024-01-18 14:13 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public class ExampleStyle
Done

2024-01-18 14:13 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public class UsageStyle
Done

2024-01-18 14:13 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public class DescriptionStyle
Done

2024-01-18 14:14 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +public class HelpProviderStyle
Done

2024-01-18 14:14 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Help/HelpProviderStyles.cs
> +    private static HelpProviderStyle? defaultStyle;
Done

2024-01-18 14:19 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Internal/Composer.cs
> +        this.renderMarkup = renderMarkup;
Done

2024-01-18 14:19 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Internal/Composer.cs
> +    private readonly StringBuilder content;
Done

2024-01-18 14:19 UTC, FrankRay78 commented on src/Spectre.Console.Cli/Internal/Composer.cs
> +    private readonly bool renderMarkup = false;
Done

2024-01-18 14:21 UTC, patriksvensson approved these changes

2024-01-18 14:26 UTC, FrankRay78 commented
Further refactoring done, good review comments @patriksvensson.

2024-01-18 14:31 UTC, merged

2024-01-18 14:31 UTC, patriksvensson commented
Merged! Thank you for your contribution. Much appreciated! 👍