Feat/progressbar valueformatter
spectreconsole/spectre.console pull request #1414
Opened 2023-12-26 15:11 UTC by jsheely

This is related to pr https://github.com/spectreconsole/spectre.console/pull/1388 and issue https://github.com/spectreconsole/spectre.console/issues/1382

Goal is to provide formatting for number values in the progress bar

- [x] I have read the [Contribution Guidelines](../CONTRIBUTING.md)
- [x] I have commented on the issue above and discussed the intended changes
- [x] A maintainer has signed off on the changes and the issue was assigned to me
- [x] All newly added code is adequately covered by tests
- [x] All existing tests are still running without errors
- [ ] The documentation was modified to reflect the changes _OR_ no documentation changes are required.

2023-12-26 15:39 UTC, patriksvensson requested changes
Looks good to me, but we should probably add an extension as well so it's consistent with other widgets yhat supports custom formatting.

We will also need to update the documentation somit reglects the new additions.

2023-12-26 15:39 UTC, patriksvensson commented on test/Spectre.Console.Tests/Unit/Widgets/ProgressBarTests.cs
> +        // Then
Space between when and then clause.

2023-12-26 15:39 UTC, patriksvensson commented on test/Spectre.Console.Tests/Unit/Widgets/ProgressBarTests.cs
> +        // Then
Space between when and then clause.

2023-12-26 15:39 UTC, patriksvensson commented on test/Spectre.Console.Tests/Unit/Widgets/ProgressBarTests.cs
> +        var bar = new ProgressBar() { Width = 60, Value = 9000, MaxValue = 9000, ShowValue = true };
Put each property on each own line.

2023-12-26 16:13 UTC, patriksvensson requested changes
Looks good but docs need to be updated.

2023-12-26 16:13 UTC, patriksvensson commented on src/Spectre.Console/Extensions/BarChartExtensions.cs
> +    /// <returns>The same instance so that multiple calls can be chained.</returns>
Documentation does not reflect the method.

2023-12-26 16:13 UTC, patriksvensson commented on src/Spectre.Console/Extensions/BarChartExtensions.cs
> +    public static BarChart UseValueFormatter(this BarChart chart, Func<double, CultureInfo, string>? func)
No documentation

2023-12-27 22:04 UTC, jsheely commented
Not sure I know what this Pull Request / Documentation error is about

```
Error: Inputs/Process » ExecuteIf » ExtractFrontMatter » ParseYaml » [/home/runner/work/spectre.console/spectre.console/docs/input/widgets/breakdownchart.md => widgets/breakdownchart.md] (Line: 4, Col: 13, Idx: 126) - (Line: 4, Col: 13, Idx: 126): Block sequence entries are not allowed in this context.
```

2024-01-31 16:36 UTC, patriksvensson approved these changes

2024-01-31 16:37 UTC, merged

2024-01-31 16:37 UTC, patriksvensson commented
Merged! Thank you for your contribution. Much appreciated! 👍