Fixing #1507 AddDelegate uses an abstract type when used in a branch
spectreconsole/spectre.console pull request #1509
Opened 2024-04-09 12:42 UTC by BlazeFace

fixes #1507 

- [ x] I have read the [Contribution Guidelines](https://github.com/spectreconsole/spectre.console/blob/main/CONTRIBUTING.md)
- [ x] I have commented on the issue above and discussed the intended changes
- [ x] A maintainer has signed off on the changes and the issue was assigned to me
- [ x] All newly added code is adequately covered by tests
- [ x] All existing tests are still running without errors
- [ x] The documentation was modified to reflect the changes _OR_ no documentation changes are required.

## Changes
Adds a check if the settings used in the add delegate call have been defined and are therefor not abstract, if not it uses empty command settings. 

Added tests for both single and double nested calls.

There may be another C# feature to accomplish this but I was unable to find any!

2024-04-09 12:44 UTC, BlazeFace commented
@microsoft-github-policy-service agree

2024-04-09 21:50 UTC, FrankRay78 commented
Thanks, I'll make time to look at this over the coming days,

2024-04-12 21:13 UTC, FrankRay78 requested changes
Looks good, a couple of minor changes please.

2024-04-12 21:13 UTC, FrankRay78 commented on test/Spectre.Console.Cli.Tests/Unit/CommandAppTests.cs
> +    public void Should_Pass_Case_7()
Circca line 1104 much further down, there is a nested test class called `Delegate_Commands` - can we please move this test into that class, and rename it accordingly please.

2024-04-12 21:13 UTC, FrankRay78 commented on test/Spectre.Console.Cli.Tests/Unit/CommandAppTests.cs
> +    public void Should_Pass_Case_8()
Circca line 1104 much further down, there is a nested test class called `Delegate_Commands` - can we please move this test into that class, and rename it accordingly please.

2024-04-13 01:14 UTC, BlazeFace commented on test/Spectre.Console.Cli.Tests/Unit/CommandAppTests.cs
> +    public void Should_Pass_Case_7()
Updated!

2024-04-13 01:15 UTC, BlazeFace commented on test/Spectre.Console.Cli.Tests/Unit/CommandAppTests.cs
> +    public void Should_Pass_Case_8()
Updated naming!

2024-04-13 12:39 UTC, FrankRay78 approved these changes

2024-04-13 12:40 UTC, merged

2024-04-13 12:40 UTC, FrankRay78 commented
Thank you @BlazeFace, very much appreciated.  Please don't hesitate to submit other high-quality PR's like this one.