Fixing #1390
spectreconsole/spectre.console pull request #1514
Opened 2024-04-14 00:27 UTC by BlazeFace

fixes #1390 

- [x] I have read the [Contribution Guidelines](https://github.com/spectreconsole/spectre.console/blob/main/CONTRIBUTING.md)
- [x] I have commented on the issue above and discussed the intended changes
- [ ] A maintainer has signed off on the changes and the issue was assigned to me
- [x] All newly added code is adequately covered by tests
- [x] All existing tests are still running without errors
- [x] The documentation was modified to reflect the changes _OR_ no documentation changes are required.

## Changes

Updated the ratio calculation to round up if the remainder is within 0.9999 I have tested this with a good amount of examples and it still works, but I have not written any proof that this will remain correct at any value. We could use a much smaller target to round say .99 as well.

2024-04-14 00:28 UTC, BlazeFace commented
@patriksvensson The only major modification I was considering was a bounds check to see if the total height could go over the target, do you think that is needed?

2024-07-31 11:22 UTC, FrankRay78 commented
I'll review this @BlazeFace

2024-10-25 00:12 UTC, BlazeFace commented
@FrankRay78 if we are looking to merge this I can go ahead and rebase and resolve conflicts.

2024-10-26 00:50 UTC, BlazeFace commented
@FrankRay78 Rebase complete

2024-10-26 10:22 UTC, FrankRay78 commented on src/Tests/Spectre.Console.Tests/Unit/Widgets/LayoutTests.cs
> +    [Fact]
Should we make this a [Theory] and pass in the problematic console heights 17, 20, 23, 28, 31 ?

2024-10-26 10:24 UTC, FrankRay78 commented on src/Tests/Spectre.Console.Tests/Unit/Widgets/LayoutTests.cs
> +    [Expectation("Render_Layout_With_Three_And_One_Columns")]
I think this/the underlying expectation file should probably be renamed to `Render_Layout_With_Nested_Three_Rows_In_One_Column`, to be more consistent with:

![image](https://github.com/user-attachments/assets/3d848a61-6a03-4257-9bca-9f340c455248)

2024-10-26 10:28 UTC, FrankRay78 commented on src/Tests/Spectre.Console.Tests/Unit/Widgets/LayoutTests.cs
> +    public Task Should_Render_Layout_With_Three_And_One_Columns()
Could you please move this to line 156, so your test follows directly after `public Task Should_Render_Layout_With_Nested_Rows_And_Columns()`, which is a natural grouping.

2024-10-26 10:32 UTC, FrankRay78 commented on src/Tests/Spectre.Console.Tests/Unit/Widgets/LayoutTests.cs
> +        }
I've thought about this, and whilst I'm happy with the correctness of the above test, all the other tests in the same file use a fluent convention. Can you please have a go at updating your test to be in the same style as the others, here's a close example to follow (I'm sorry for this 🏈 ache request, and I know the test comes direct from the issue repro code):

```csharp
    public Task Should_Render_Layout_With_Nested_Rows_And_Columns()
    {
        // Given
        var console = new TestConsole().Size(new Size(40, 15));
        var layout = new Layout()
            .SplitRows(
                new Layout("Top")
                    .SplitRows(
                        new Layout("T1")
                            .SplitColumns(
                                new Layout("A"),
                                new Layout("B")),
                        new Layout("T2")
                            .SplitColumns(
                                new Layout("C"),
                                new Layout("D"))),
                new Layout("Bottom")
                    .SplitRows(
                        new Layout("B1")
                            .SplitColumns(
                                new Layout("E"),
                                new Layout("F")),
                        new Layout("B2")
                            .SplitColumns(
                                    new Layout("G"),
                                    new Layout("H"))));

        // When
        console.Write(layout);

        // Then
        return Verifier.Verify(console.Output);
    }
```

2024-10-26 10:34 UTC, FrankRay78 requested changes
Hello @BlazeFace, if you'll be kind enough to entertain my review feedback, I'll be most kind enough to merge the PR once done. (So you know your efforts won't languish in an unmerged PR).

2024-10-26 14:26 UTC, BlazeFace commented on src/Tests/Spectre.Console.Tests/Unit/Widgets/LayoutTests.cs
> +    [Fact]
Done!

2024-10-26 14:26 UTC, BlazeFace commented on src/Tests/Spectre.Console.Tests/Unit/Widgets/LayoutTests.cs
> +    [Expectation("Render_Layout_With_Three_And_One_Columns")]
Done!

2024-10-26 14:26 UTC, BlazeFace commented on src/Tests/Spectre.Console.Tests/Unit/Widgets/LayoutTests.cs
> +    public Task Should_Render_Layout_With_Three_And_One_Columns()
Done!

2024-10-26 14:26 UTC, BlazeFace commented on src/Tests/Spectre.Console.Tests/Unit/Widgets/LayoutTests.cs
> +        }
Done!

2024-10-27 16:22 UTC, FrankRay78 commented
Thanks @BlazeFace, I've seen lots of activity but not had the time to look just yet. But I will do so soon.

2024-10-27 16:44 UTC, patriksvensson approved these changes
LGTM 👍

2024-10-28 16:49 UTC, FrankRay78 commented
Good stuff @BlazeFace. Don't hesitate to tag me when you have other PRs to review.

2024-10-28 20:12 UTC, patriksvensson commented
@FrankRay78 I think you forgot to approve and merge 😉

2024-10-28 22:56 UTC, FrankRay78 commented
A teacher knows to be humble before the master.

2024-10-30 00:36 UTC, merged

2024-10-30 00:36 UTC, patriksvensson commented
LGTM 👍