Character cells count perf
spectreconsole/spectre.console pull request #340
Opened 2021-04-04 17:28 UTC by phil-scott-78

I noticed that we spend a lot of time calculating widths of strings and their rune size. E.g. to render the progress demo, it is over 1,000,000 measurements. This is a proposal to cache those values for quick access.

Because there are a limited number of runes this adds a static array to cache them that we can then just go right to their memory spot without needing to hit WcWidth for these values. Being able to quickly grab these values drops rendering time significantly, especially if we are rendering something repeatably like a progress bar.

# Simple example using the tables demo.

Before
![image](https://user-images.githubusercontent.com/2447331/113515954-9e891c80-9545-11eb-9e0c-7b158900aa59.png)

After
![image](https://user-images.githubusercontent.com/2447331/113515964-a8128480-9545-11eb-9691-1713747904f4.png)

# More Complex

Here's one rendering a tree. Nearly an entire second was spent counting characters

Before
![image](https://user-images.githubusercontent.com/2447331/113516012-f9bb0f00-9545-11eb-948e-9ee3763defb7.png)

After
![image](https://user-images.githubusercontent.com/2447331/113515997-de500400-9545-11eb-956d-b33485dd4e81.png)

# Even More Complex.

Running the progress demo shows even more improvements. shaves 3 seconds off of the millions of calculations we do.

Before
![image](https://user-images.githubusercontent.com/2447331/113516502-98486f80-9548-11eb-871d-73842af6756d.png)

After
![image](https://user-images.githubusercontent.com/2447331/113516526-b0b88a00-9548-11eb-89c3-32d72bf0e5e4.png)

Downside, of course, is we are eating up 65kb to store this data but that's a pretty fair tradeoff. Might make sense to looking at reducing the calls to the method to begin long term.

2021-04-04 17:29 UTC, phil-scott-78 commented
man did I screw something up rebasing my local against the main branch. ignore those commits. I'll get that straightened up once the kiddo takes a nap.

2021-04-04 17:49 UTC, phil-scott-78 commented
well things went totally squirelly. Disregard for now, I've done terribly dumb.

2021-04-04 18:06 UTC, phil-scott-78 commented
And on the third `git push --force`, the build is risen.

2021-04-04 19:32 UTC, phil-scott-78 commented
I'm going to try a few more benchmarks, so hold off on a merge for now.

2021-04-04 23:00 UTC, phil-scott-78 commented
Ok, I feel pretty good about the speed. Used BenchmarkDotNet to calculate the cell length of 1000 random strings company names from Bogus. Here are the results.

|      Method |      Mean |    Error |   StdDev |
|------------ |----------:|---------:|---------:|
|    Original | 907.34 us | 6.609 us | 5.858 us |
|   WithCache |  60.90 us | 0.555 us | 0.519 us |

Of course, this means that the original method is averaging less than one-microsecond. But with us doing potentially millions of them it's worth it. FWIW, I also tested out using 

```csharp
StringInfo.ParseCombiningCharacters(text).Length
```

but not only did it break the tests with things like chinese characters, but it was also 10x slower than the cached character implementation.

2021-04-06 20:34 UTC, patriksvensson requested changes
Looks good to me. Just a minor nitpicking thing that needs to be fixed 😅

2021-04-06 20:34 UTC, patriksvensson commented on src/Spectre.Console/Internal/Cell.cs
> + }
@phil-scott-78 There seems to be something wrong with the indentation here.

2021-04-06 22:50 UTC, phil-scott-78 commented
good catch. fixed that up and ammended the commit

2021-04-06 22:58 UTC, patriksvensson approved these changes
LGTM!

2021-04-07 21:59 UTC, merged