Adds CLI explain command
spectreconsole/spectre.console pull request #345
Opened 2021-04-05 14:15 UTC by phil-scott-78

Wanted a command to break down how Spectre views the command model. This outputs all the relevant settings in a tree. You can get a short explanation for all the commands, or a detailed explanation for all commands (there is a flag to go vice versa on the detailed view if you want)

```
app cli explain
app cli explain myappcommand
app cli explain -d
```

I honestly only included the output that I think is helpful for my use cases, so I'm sure I missed something. Feel free to suggest new data, better, formatting or what-have-you!

2021-04-06 20:45 UTC, patriksvensson approved these changes

2021-04-06 20:59 UTC, patriksvensson requested changes
Some nitpicking things, but otherwise this looks good to me!

2021-04-06 20:59 UTC, patriksvensson commented on src/Spectre.Console/Cli/Internal/Commands/ExplainCommand.cs
> +    internal class ExplainCommand : Command<ExplainCommand.Settings>
I prefer that we seal classes that are not designed for (further) inheritance.

2021-04-06 20:59 UTC, patriksvensson commented on src/Spectre.Console/Cli/Internal/Commands/ExplainCommand.cs
> +            _commandModel = commandModel;
```suggestion
            _commandModel = commandModel ?? throw new ArgumentNullException(nameof(commandModel));
```

2021-04-06 20:59 UTC, patriksvensson commented on src/Spectre.Console/Cli/Internal/Commands/ExplainCommand.cs
> +            public string[]? Command { get; set; } = null;
Rename this to `Commands` or similar?

2021-04-07 15:15 UTC, phil-scott-78 commented
Pushed up a change with the requests featured. I also rebased on main to get the nullable constructor bugfixes from earlier and adjusted the `Settings` to use a constructor with get only properties.

2021-04-08 00:35 UTC, phil-scott-78 commented
ok, now the changes are there. My git client was sitting there asking me to confirm a git force for 9 hours.

2021-04-12 15:40 UTC, patriksvensson approved these changes
LGTM!

2021-04-12 15:40 UTC, merged