Add blog to docs
spectreconsole/spectre.console pull request #484
Opened 2021-07-13 03:53 UTC by phil-scott-78

I want to checkout the output generated from the CI and make sure things don't get squirelly with github actions and playwright. But if that works this might just be ready. 

I'm still not 100% pleased with the index page for the categories, but they still look ok there and aren't going to be very frequently traveled pages anyways.

2021-07-13 04:10 UTC, phil-scott-78 commented
Cleaned up some CI errors that popped up then verified the artifact that the docs look good. 

Might be some spelling mistake and the first post isn't exactly pulitzer award winning material, but I feel good about the tech side of things at least :-)

2021-07-15 07:38 UTC, patriksvensson requested changes
Looks good to me, but found one thing that might need to be fixed

2021-07-15 07:38 UTC, patriksvensson commented on .github/workflows/ci.yaml
> +        dotnet-version: 6.0.x
I think this change will need to be done in `publish.yaml` as well

2021-07-15 12:15 UTC, phil-scott-78 commented on .github/workflows/ci.yaml
> +        dotnet-version: 6.0.x
oh great catch. got that updated to 6.0.x with the latest push

2021-07-15 17:51 UTC, patriksvensson approved these changes
LGTM 👍

2021-07-15 17:53 UTC, merged

2021-07-15 17:53 UTC, patriksvensson commented
Merged! 🎉