Add support custom max value for barcharts
spectreconsole/spectre.console pull request #545
Opened 2021-09-23 19:31 UTC by rifatx

With this PR, it will be possible to set a custom max value for barcharts, so that multiple charts could be visually aligned.

This PR closes issue #524.

2021-09-23 19:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/spectreconsole/spectre.console?pullRequest=545) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/spectreconsole/spectre.console?pullRequest=545) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/spectreconsole/spectre.console?pullRequest=545) it.</sub>

2021-09-23 20:31 UTC, patriksvensson requested changes
LGTM apart from a minor thing 👍

2021-09-23 20:31 UTC, patriksvensson commented on src/Spectre.Console/Widgets/Charts/BarChart.cs
> +        public double MaxValue { get; set; } = 0;
Perhaps this could be nullable to indicate that no explicit max value has been set?

2021-09-24 06:24 UTC, rifatx commented on src/Spectre.Console/Widgets/Charts/BarChart.cs
> +        public double MaxValue { get; set; } = 0;
makes sense 👍 updated the PR.

2021-09-27 08:53 UTC, patriksvensson requested changes

2021-09-27 08:53 UTC, patriksvensson commented on src/Spectre.Console/Extensions/BarChartExtensions.cs
> +        public static BarChart WithFixedMaxValue(this BarChart chart, double maxValue)
Could we rename this to `WithMaxValue` instead?

2021-09-27 17:32 UTC, rifatx commented on src/Spectre.Console/Extensions/BarChartExtensions.cs
> +        public static BarChart WithFixedMaxValue(this BarChart chart, double maxValue)
👍

2021-09-28 18:19 UTC, patriksvensson approved these changes
LGTM!

2021-10-04 22:47 UTC, patriksvensson approved these changes

2021-10-04 22:49 UTC, merged

2021-10-04 22:49 UTC, patriksvensson commented
Merged! Thank you for your contribution. Much appreciated! 👍