Remove `Render` from docs in favor of `Write`
spectreconsole/spectre.console pull request #613
Opened 2021-11-07 11:24 UTC by patriksvensson

The `Render` method has been obsoleted.

2021-11-08 20:35 UTC, nils-a requested changes
Overall it's good.
However, I think you missed 
[`docs/input/markup.md`](https://github.com/spectreconsole/spectre.console/blob/main/docs/input/markup.md?plain=1#L18) and [`docs/input/widgets/calendar.md`](https://github.com/spectreconsole/spectre.console/blob/main/docs/input/widgets/calendar.md?plain=1#L19)

2021-11-08 23:19 UTC, patriksvensson commented
@nils-a Done!

2021-11-09 20:21 UTC, nils-a reviewed
LGTM!

2021-11-09 20:22 UTC, nils-a approved these changes

2021-11-09 20:22 UTC, merged