Fix #587: Support negative numbers as command option values
spectreconsole/spectre.console pull request #732
Opened 2022-02-16 19:55 UTC by jouniheikniemi

2022-02-27 02:25 UTC, phil-scott-78 reviewed
Had some time to look through this. At a glance it looks good. But think we could get some tests that cover the invalid cases as described in the comments of the tokenizer for invalid items?

2022-03-01 19:49 UTC, jouniheikniemi commented
Hey @phil-scott-78, thanks for reviewing. Actually, CommandTreeTokenizer does have (logical) 100 % test coverage already. It is not immediately obvious, as this PR is the first stage that actually adds tests specifically for the Tokenizer; previously, the tokenizer has only been tested through CommandAppTests which test the entire parsing and execution pipeline. However, some of the test scenarios there (say, CommandAppTests.Parsing.InvalidShortOptionName.Should_Return_Correct_Text) do exercise these failure modes.

I would personally prefer to have 100 % coverage specifically with the tokenizer test suite, but writing all that is slightly beyond the scope of this issue. Would you expect to see (tokenizer level) tests for the failure scenarios of the ScanShortOptions tokenizer branch or what? TBH, the tokenizer test set in this PR doesn't cover all short option tokenization features (even the happy paths) either, grouped properties probably being the most important missing part. Given that there's no precedent for tokenizer tests in the project, I'm happy to do extra work to set a good example, let's just agree on the goal first.

2022-10-28 10:22 UTC, FrankRay78 requested changes
Thank you for submitting this PR, my review comments are largely stylistic to ensure the changes fit stylistically with the rest of the codebase.

2022-10-28 10:22 UTC, FrankRay78 commented on src/Spectre.Console/Cli/Internal/Parsing/CommandTreeTokenizer.cs
> +                ThrowInvalidShortOptionName(current.ToString(CultureInfo.InvariantCulture));
I do not see the benefit of putting the local three-line logic into a separate private method, which also still references `reader.Original` from the calling function without passing this in as an explicit argument.  I suggest this private method be removed and the logic relocated inline here, instead.

2022-10-28 10:22 UTC, FrankRay78 commented on test/Spectre.Console.Tests/Unit/Cli/CommandTreeTokenizerTests.cs
> +public static class CommandTreeTokenizerTests
Fantastic that you have introduced explicit unit tests for the tokenizer! A positive move away from the general approach of 'unit tests' being located at the CommandApp level (nb. more like integration tests really).

Does this class need to be static?  Unit test classes aren't generally made static - suggest this is also removed to ensure consistency with the rest of the codebase.

2022-10-28 10:22 UTC, FrankRay78 commented on test/Spectre.Console.Tests/Unit/Cli/CommandTreeTokenizerTests.cs
> +        {
// When

2022-10-28 10:22 UTC, FrankRay78 commented on test/Spectre.Console.Tests/Unit/Cli/CommandTreeTokenizerTests.cs
> +
// Then

2022-10-28 10:22 UTC, FrankRay78 commented on test/Spectre.Console.Tests/Unit/Cli/CommandTreeTokenizerTests.cs
> +        {
// Given

2022-10-28 10:22 UTC, FrankRay78 commented on test/Spectre.Console.Tests/Unit/Cli/CommandTreeTokenizerTests.cs
> +
// When

2022-10-28 10:22 UTC, FrankRay78 commented on test/Spectre.Console.Tests/Unit/Cli/CommandTreeTokenizerTests.cs
> +
// Then

2022-10-28 10:22 UTC, FrankRay78 commented on test/Spectre.Console.Tests/Unit/Cli/CommandTreeTokenizerTests.cs
> +        {
// When

2022-10-28 10:22 UTC, FrankRay78 commented on test/Spectre.Console.Tests/Unit/Cli/CommandTreeTokenizerTests.cs
> +            Assert.Empty(result.Remaining);
// Then

2022-10-28 10:36 UTC, FrankRay78 commented
> this PR is the first stage that actually adds tests specifically for the Tokenizer; previously, the tokenizer has only been tested through CommandAppTests which test the entire parsing and execution pipeline

This is a significant improvement that @jouniheikniemi has introduced and I would be keen to see this PR, once review comments are addressed 😊, merged into the codebase.  Particularly since I have a raft of CommandTreeTokenizer tests I would like to add myself, ideally into the same class being introduced in this PR.

2022-11-05 11:59 UTC, FrankRay78 commented
This should be closed as it's been fully included in https://github.com/spectreconsole/spectre.console/pull/1048  [I don't have permission to close another person's PR]

2022-11-06 19:02 UTC, jouniheikniemi commented
I was about to get back to your review comments, but it seems you'd rather pick up the ball yourself; fine with me. Closing the PR. Thanks!

2022-11-06 19:02 UTC, closed without merging

2022-11-07 09:32 UTC, FrankRay78 commented
I was keen to merge your excellent work @jouniheikniemi - thanks for your contribution.