Updated Microsoft.CodeAnalysis.* to current versions
spectreconsole/spectre.console pull request #804
Opened 2022-04-05 12:37 UTC by nils-a

* Microsoft.CodeAnalysis.Analyzers to 3.3.3
* Microsoft.CodeAnalysis.CSharp to 4.1.0
* Microsoft.CodeAnalysis.CSharp.Workspaces to 4.1.0
* Microsoft.CodeAnalysis.CSharp.Analyzer.Testing.XUnit to 1.1.1
* Microsoft.CodeAnalysis.CSharp.CodeFix.Testing.XUnit to 1.1.1

Afterwards fixed warnings in the code that resulted from the updates.

2022-04-07 08:27 UTC, patriksvensson approved these changes
LGTM!

2022-04-07 08:30 UTC, patriksvensson requested changes
Checks are failing, otherwise, it looks good to me.

2022-04-10 21:11 UTC, nils-a commented
Need to work on this one. Not sure why the CI fails. Build works on my Windows and Ubuntu (18.04) environments, as well as a clean Ubuntu 20.04 installation.

2022-07-02 09:19 UTC, patriksvensson commented
I had to fix this while doing #877, so I'm going to close this one out.

2022-07-02 09:19 UTC, closed without merging