Adding TransferSpeedColumn configuration to display bits/bytes + binary/decimal prefixes
spectreconsole/spectre.console pull request #904
Opened 2022-07-22 23:14 UTC by tpill90

## Context

Currently the `TransferSpeedColumn` is displaying the transfer speed using the binary/IEC definition of a kilobyte/megabyte/gigabyte (1024<sup>x</sup>)

Typically, network transfer speeds are specified using the decimal definition (1000<sup>x</sup>), for example Ethernet (10/100/1000BASE-T), or internet connection speeds (100mbit = 100,000,000,000)

https://en.wikipedia.org/wiki/Binary_prefix#Data_transmission_and_clock_rates

## Describe the solution you'd like

I would like to propose adding the ability to configure which binary prefix (1000<sup>x</sup> or 1024<sup>x</sup>) is used for display, as well as configuring to display either **bits/s** or **bytes/s**.  This would allow developers to be able to tweak formatting to better match their use case.

The default display format would be to continue to use the current format, 1024<sup>x</sup> , as to ensure that there are no unexpected changes to the existing behavior when updating to a newer version of the package. 

Using a data transfer rate of **1,000,000** bytes, the expected output for each configurablee option would be as follows :

| Binary Prefix | Bits/Bytes | Expected Output |
| ------------- | ---------- | --------------- |
| Binary        | bytes      |  .95 MiB/s  |
| Decimal       | bytes      |    1 MB/s   |
| Binary        | bits       | 7.63 Mibit/s |
| Decimal       | bits       |    8 Mbit/s |

## Testing
These changes have been in use for about a month now in my projects [steam-lancache-prefill](https://github.com/tpill90/steam-lancache-prefill) and [battlenet-lancache-prefill](https://github.com/tpill90/Battlenet-lancache-prefill), and have been able to be tested and proven to be working, as well as being able to smooth over any unexpected edge cases.

Example output of the change : 
![image](https://user-images.githubusercontent.com/766513/180579505-15fa8bbf-de8f-4041-a2c8-09455eef0c8c.png)
[Related commit, where changes started to be used](https://github.com/tpill90/Battlenet-lancache-prefill/commit/53a064985fd66a18046eae9eaace3de47e2e9b11)

2022-07-22 23:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/spectreconsole/spectre.console?pullRequest=904) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/spectreconsole/spectre.console?pullRequest=904) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/spectreconsole/spectre.console?pullRequest=904) it.</sub>

2023-03-03 03:22 UTC, tpill90 commented
@patriksvensson @phil-scott-78 Could I kindly ask for your thoughts and feedback on these changes whenever you have some time to take a look?  I'd be more than happy to discuss the changes in further details, and I would be glad to know if there is anything I can do to help get these changes included.  Thank you!

2024-11-01 11:34 UTC, FrankRay78 commented
Hey @tpill90, looks like an interesting, well drafted PR - are you still around to help me get this reviewed/merged? (assuming I might need your help, although perhaps we get lucky with a straight merge...).  I assume you'd like this for https://github.com/tpill90/steam-lancache-prefill ? (which looks awesome btw)?

2024-11-04 11:59 UTC, FrankRay78 commented
I like this PR @tpill90 and have started reviewing it.  Solid code.

2024-11-07 21:22 UTC, FrankRay78 requested changes
Brain dump of my review comments.

2024-11-07 21:22 UTC, FrankRay78 commented on test/Spectre.Console.Tests/Unit/Internal/FileSizeTests.cs
> +public sealed class FileSizeTests
nb. When I rebased your PR against main, due to a solution restructure since you took the fork 2 years ago, I needed to move the following file location:

![image](https://github.com/user-attachments/assets/7cf61cff-8303-4031-a2a3-2c3f8f98abb9)

2024-11-07 21:22 UTC, FrankRay78 commented on test/Spectre.Console.Tests/Unit/Live/Progress/DownloadedColumnTests.cs
>          var fixture = new ProgressColumnFixture<DownloadedColumn>(value, total);
Having the `new FileSize` embedded inside the `DownloadedColumn.Render` means that we cannot configure the Fixture for Decimal/Binary/Bits Y/Bits N combinations - we need a better way to do this (this same issue will affect Spectre.Console users when they come to use the DownloadedColumn).

I'm wondering if we should create a `FileSizeSettings` class, that has the following properties on it (stolen from TransferSpeedColumn):

```
    /// <summary>
    /// Gets or sets the <see cref="FileSizeBase"/> to use.
    /// </summary>
    public FileSizeBase Base { get; set; } = FileSizeBase.Binary;

    /// <summary>
    /// Gets or sets a value indicating whether or not to display the transfer speed in bits.
    /// </summary>
    public bool DisplayBits { get; set; }
```

and somehow `FileSizeSettings` can be set on both `DownloadedColumn` and `TransferSpeedColumn`, both by the Spectre.Console user and also when using `ProgressColumnFixture`

Other suggestions/ideas welcome.

2024-11-07 21:22 UTC, FrankRay78 commented on src/Spectre.Console/Internal/FileSize.cs
> +    private readonly bool _displayBits = false;
The rest of the codebase seems to standardise on the word 'show' in settings like this - I recommend we rename 'DisplayBits' (and case variations) to 'ShowBits', simply for consistency.

2024-11-12 13:49 UTC, tpill90 commented
Hey Frank,  I apologize for not getting a chance to look at it yet. I'm going to try to get to it today. Thanks for your help on this

2024-11-13 00:01 UTC, tpill90 commented on src/Spectre.Console/Internal/FileSize.cs
> +    public readonly FileSizeBase Base = FileSizeBase.Binary;
I had to do some more testing to remember why I ended up picking Binary as the default here.  Spectre.Console was actually already doing its transfer rates in binary, it was just displaying the incorrect unit.

I did some testing with my 300mbit internet connection, and tested how the transfer rate is being displayed in the nuget version of the library, and compared it against the default of `FileSizeBase.Binary` in my PR.  Both versions display the transfer rate as "36" which roughly corresponds to the conversion of `300mbit` to `35.7628MiB`.  Give or take a little since network connections aren't perfectly flat.

![image](https://github.com/user-attachments/assets/4ef45730-c027-429f-9a97-78b05cf381fe)

Now if I rerun my PR version using `FileSizeBase.Decimal` then I get around 38 MB/s, which matches the conversion of `300mbit` to `37.5MB`.  Again, fluctuating network transfers make it a bit off, but its in the correct ballpark.

![image](https://github.com/user-attachments/assets/e53a80a9-8435-4435-b862-2b70d6aa6261)

2024-11-13 00:20 UTC, tpill90 commented on src/Spectre.Console/Live/Progress/Columns/DownloadedColumn.cs
> +        var total = new FileSize(task.MaxValue);
Good catch, I didn't think of this originally.  Will add it in.

2024-11-13 00:24 UTC, tpill90 commented on src/Spectre.Console/Internal/FileSize.cs
> +    private readonly bool _displayBits = false;
👍 Updated.

2024-11-13 00:24 UTC, tpill90 commented on src/Spectre.Console/Internal/FileSizePrefix.cs
> +public enum FileSizeBase
👍 Done.

2024-11-13 00:32 UTC, tpill90 commented on test/Spectre.Console.Tests/Unit/Internal/FileSizeTests.cs
> +public sealed class FileSizeTests
ty.

2024-11-13 00:49 UTC, tpill90 commented on test/Spectre.Console.Tests/Unit/Live/Progress/DownloadedColumnTests.cs
>          var fixture = new ProgressColumnFixture<DownloadedColumn>(value, total);
I'm not sure I'm tracking here.  Wouldn't it just be as simple as:
```
.Columns(new ProgressColumn[] 
    {
        new DownloadedColumn() { Base = FileSizeBase.Decimal },  
		new TransferSpeedColumn { Base = FileSizeBase.Decimal }
    })
```

2024-11-13 12:31 UTC, FrankRay78 commented
I'll look at your comments/changes soon @tpill90 👏

2024-11-14 11:00 UTC, FrankRay78 commented
FYI.  The build is broken on your branch, following the rename from `DisplayBits` to `ShowBits`, see:  

![image](https://github.com/user-attachments/assets/dbc3da02-0e39-48a5-acf4-ab0f09e62182)

2024-11-14 11:10 UTC, FrankRay78 commented on src/Spectre.Console/Internal/FileSize.cs
> +    public readonly FileSizeBase Base = FileSizeBase.Binary;
Really good stuff 👏

I want to check with the other maintainers before we commit this, as whilst you've identified a bug in the current main branch, changing the default to Binary will break any output validation (that relies on the suffix) our existing users may have. Equally, I know the converse is true, ie. a default of Decimal means the suffix remains the same, but the calculated speed will change (although I strongly suspect this is less likely to be a 'breaking change'). 

Would you be kind enough to offer your opinion @patriksvensson, on the above?

2024-11-14 11:13 UTC, FrankRay78 commented on src/Spectre.Console/Internal/FileSize.cs
> +    public FileSize(double bytes, FileSizeBase prefix)
Can you rename `prefix` to `base` please?

2024-11-14 11:14 UTC, FrankRay78 commented on src/Spectre.Console/Internal/FileSize.cs
> +    public FileSize(double bytes, FileSizeBase prefix, bool showBits)
Can you rename `prefix` to `base` please?

2024-11-14 11:20 UTC, FrankRay78 commented on src/Spectre.Console/Live/Progress/Columns/DownloadedColumn.cs
> +    public bool DisplayBits { get; set; }
Should we rename `DisplayBits` to `ShowBits` to ensure consistency with the corresponding property in `FileSize`?

2024-11-14 11:20 UTC, FrankRay78 commented on src/Spectre.Console/Live/Progress/Columns/TransferSpeedColumn.cs
> +    public bool DisplayBits { get; set; }
Should we rename `DisplayBits` to `ShowBits` to ensure consistency with the corresponding property in `FileSize`?

2024-11-14 11:22 UTC, FrankRay78 commented on src/Spectre.Console/Live/Progress/Columns/TransferSpeedColumn.cs
> +    public FileSizeBase Base { get; set; } = FileSizeBase.Binary;
**Note to self** - final decision whether to standardise on Binary or Decimal is pending input from the other Spectre.Console maintainers (which has been asked above, in another review comment).

2024-11-14 11:39 UTC, FrankRay78 commented on test/Spectre.Console.Tests/Unit/Live/Progress/DownloadedColumnTests.cs
>          var fixture = new ProgressColumnFixture<DownloadedColumn>(value, total);
Apologies, I didn't explain myself very well.  See the following test:

```csharp
    public void Should_Return_Correct_Value(double value, double total, string expected)
    {
        // Given
        var fixture = new ProgressColumnFixture<DownloadedColumn>(value, total);
        fixture.Column.Culture = CultureInfo.InvariantCulture;
```

`ProgressColumnFixture` is actually creating the `DownloadedColumn` object within it's own constructor, see here:

```csharp
    public T Column { get; }
    public ProgressTask Task { get; set; }

    public ProgressColumnFixture(double completed, double total)
    {
        Column = new T();    //    <----  HERE
        Task = new ProgressTask(1, "Foo", total);
```

So currently, the unit tests cannot set properties like you suggest here:

```csharp
        new DownloadedColumn() { Base = FileSizeBase.Decimal },  
		new TransferSpeedColumn { Base = FileSizeBase.Decimal }
```

I think we need the ability to pass in an already instantiated `ProgressColumn` into the `ProgressColumnFixture` ?

2024-11-14 11:41 UTC, FrankRay78 commented on test/Spectre.Console.Tests/Unit/Live/Progress/DownloadedColumnTests.cs
>      public void Should_Return_Correct_Value(double value, double total, string expected)
**Note to self** - better explained the implications further down, here: https://github.com/spectreconsole/spectre.console/pull/904#discussion_r1842076346

2024-11-14 11:43 UTC, FrankRay78 commented on src/Spectre.Console/Live/Progress/Columns/DownloadedColumn.cs
> +    public FileSizeBase Base { get; set; } = FileSizeBase.Binary;
**Note to self** - default value TBD by Spectre.Console maintainers.

2024-11-14 17:48 UTC, patriksvensson commented on src/Spectre.Console/Live/Progress/Columns/DownloadedColumn.cs
> +    public FileSizeBase Base { get; set; } = FileSizeBase.Binary;
I vote for `Binary`

2024-11-14 19:45 UTC, tpill90 commented on test/Spectre.Console.Tests/Unit/Live/Progress/DownloadedColumnTests.cs
>          var fixture = new ProgressColumnFixture<DownloadedColumn>(value, total);
I see what you're saying now.  I just ended up doing them like this, which was already in line with what the original tests were doing with setting the Culture.  

```
 var fixture = new ProgressColumnFixture<DownloadedColumn>(value, total);
 fixture.Column.Culture = CultureInfo.InvariantCulture;
 fixture.Column.Base = FileSizeBase.Binary;
 fixture.Column.ShowBits = false;
```

I could certainly refactor it out to have the column be passed in if needed.

2024-11-14 19:48 UTC, tpill90 commented
I pushed up another commit which should take care of the latest comments you've left on the review @FrankRay78 .

A follow up question,  what documentation should I be updating with this PR?  I'll gladly update it, I just was waiting for things to get closer to being merged before going through all of it 😄

2024-11-14 19:55 UTC, FrankRay78 commented
I've been thinking about documentation. Strictly speaking, the xml comments on things like the ShowBits property will end up in the auto generated API reference, however I notice the Progress page code example doesn't include the Download progress column, see: https://spectreconsole.net/live/progress

I think it might be enough to just add that into the example, so it becomes obvious to casual readers that such a thing exists.

2024-11-16 12:24 UTC, FrankRay78 commented on src/Spectre.Console/Internal/FileSize.cs
> +    public readonly FileSizeBase Base = FileSizeBase.Binary;
We've agreed on `Binary`

2024-11-16 13:08 UTC, FrankRay78 commented
Frigging awesome coding @tpill90, I think we are good with the PR review.  

I'm just looking at the documentation and playing around with some exploratory use of the Download/Transfer speed columns to get a better idea of what we might want to explain to users.

Feel free to do the same, and/or I'll write my suggestion once done.  We can always discuss if we have differences of opinion.

2024-11-18 15:14 UTC, FrankRay78 commented
FYI. I've suggested a couple of final changes, [here](https://github.com/tpill90/spectre.console/pull/2) to consider, prior to merging.

2024-11-19 02:05 UTC, tpill90 commented
> FYI. I've suggested a couple of final changes, [here](https://github.com/tpill90/spectre.console/pull/2) to consider, prior to merging.

This is merged into my branch, and is ready be merged into upstream.

Do you need me to rebase again?  Do you want me to squash or will you do that on merge?

2024-11-19 15:40 UTC, FrankRay78 approved these changes

2024-11-19 15:41 UTC, merged

2024-11-19 15:44 UTC, FrankRay78 commented
Fabulous stuff @tpill90   - it's squashed and merged.  You should get tagged when release 0.51 goes out, and the release notes are generated.

Feel free to make further contributions, particularly anything useful sitting in your own branch. Tag me into any PR's and I'll prioritise.

Feel proud of this one, and our interaction, it's been great.