Modified MarkupTokenizer, so that escaped markup inside markup is valid
spectreconsole/spectre.console pull request #911
Opened 2022-08-02 21:29 UTC by nils-a

fixes #903

2022-08-03 03:43 UTC, phil-scott-78 approved these changes
Been a minute since I've looked in here, but things look good to me. 

Maybe it has been my time away from digging into the guts, but if you have to jump back in to fix the formatting issue it might be nice to comment out the difference scenarios we are checking for in the tokenizer. The nesting is getting kind of deep and it was tough for my admittedly sleep deprived brain to follow :-)

2022-08-03 08:52 UTC, nils-a commented
Yes - it was kind of late yesterday, but I wanted to get the code out, so you could pick on it 😁 
I'm not really fond of the nesting either - I had a hard time grasping what was going on. Then again, I was never good at writing parsers. 🤷

2022-08-03 13:03 UTC, patriksvensson requested changes

2022-08-03 13:03 UTC, patriksvensson commented on src/Spectre.Console/Internal/Text/Markup/MarkupTokenizer.cs
> +                            $"Encountered unescaped ']' token at position {_reader.Position}.");
I understand the tempation to add the dot here, but we should remove it so we're consistent with the rest of the library (or change all of them) 😅

2022-08-03 13:03 UTC, patriksvensson commented on src/Spectre.Console/Internal/Text/Markup/MarkupTokenizer.cs
> +                        $"Encountered malformed markup tag at position {_reader.Position - 1}.");
See comment about punctuation.

2022-08-03 13:03 UTC, patriksvensson commented on src/Spectre.Console/Internal/Text/Markup/MarkupTokenizer.cs
> +                throw new InvalidOperationException($"Encountered unescaped ']' token at position {_reader.Position}.");
See comment about punctuation.

2022-08-03 21:11 UTC, nils-a commented on src/Spectre.Console/Internal/Text/Markup/MarkupTokenizer.cs
> +                            $"Encountered unescaped ']' token at position {_reader.Position}.");
I've reverted that change. I started to make them consistent but stopped - that is a far too big change to slide it in here 🤣

2022-08-03 21:15 UTC, nils-a commented
I've restructured the `MarkupTokenizer` a bit so that it's hopefully a bit more readable/understandable.

I let the text of the exceptions basically as they were before this PR - I'll start a PR to make the exceptions all have the "same" punctuation as soon as this one's fine.

2022-08-22 11:47 UTC, rouke-broersma commented
Thank you for fixing this! Looking forward to a release :)

2022-08-29 06:54 UTC, patriksvensson approved these changes

2022-08-29 06:54 UTC, merged