Custom mask for secret
spectreconsole/spectre.console pull request #970
Opened 2022-09-18 02:38 UTC by GaryMcD

Implemented functionality for https://github.com/spectreconsole/spectre.console/issues/943.

- Added char? to text prompt to hold character used for masking secrets.
- Added string extension to replace each char in string with mask.
- Replaced all hardcoded asterisks for secrets with new mask.

2022-09-18 02:38 UTC, GaryMcD commented
Next step is to create tests, and docs.

2022-09-18 02:58 UTC, GaryMcD commented
Tests have been created... but I am not sure how to run the tests on my local machine. @patriksvensson are you able to explain that or point me to some docs?

2022-09-18 03:10 UTC, GaryMcD commented
This should be good to go, if I can just figure out how to run tests locally.

2022-09-19 06:50 UTC, patriksvensson requested changes

2022-09-19 06:50 UTC, patriksvensson commented on examples/Console/Prompt/Program.cs
> +                    .Secret()
I was thinking, perhaps instead of adding a `Mask` extension method, we could add an overload to `Secret`?

```csharp
public static TextPrompt<T> Secret<T>(this TextPrompt<T> obj, char secret)
```

2022-09-20 07:25 UTC, GaryMcD commented on examples/Console/Prompt/Program.cs
> +                    .Secret()
I'll take a look this week.

2022-09-21 03:46 UTC, GaryMcD commented on examples/Console/Prompt/Program.cs
> +                    .Secret()
@patriksvensson resolved.

2022-09-26 18:34 UTC, patriksvensson approved these changes
LGTM! 👍

2022-09-26 18:34 UTC, merged

2022-09-26 18:34 UTC, patriksvensson commented
Merged! Thank you for your contribution. Much appreciated! 👍